# Generated by Django 4.1.7 on 2023-04-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webpages',
            new_name='Webpage',
        ),
    ]
